### ISSUE TITLE
ImportError: No module named 'terminaltables'

### ISSUE THREAD

**Issue by m-jumpi** [tosher/TSQLEasy#20]
After installation in the console:

TSQLEasy: PyODBC was loaded successfully.
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\AppData\Roaming\Sublime Text 3\Packages\TSQLEasy\tsqleasy.py", line 6, in <module>
    from .base import *
  File "C:\Users\AppData\Roaming\Sublime Text 3\Packages\TSQLEasy\base\__init__.py", line 4, in <module>
    from .te_set_active_server import TsqlEasySetActiveServerCommand
  File "C:\Users\AppData\Roaming\Sublime Text 3\Packages\TSQLEasy\base\te_set_active_server.py", line 6, in <module>
    from . import te_utils as utils
  File "C:\Users\AppData\Roaming\Sublime Text 3\Packages\TSQLEasy\base\te_utils.py", line 9, in <module>
    from ..libs.terminaltables.other_tables import WindowsTable as SingleTable
  File "C:\Users\AppData\Roaming\Sublime Text 3\Packages\TSQLEasy\libs\terminaltables\__init__.py", line 9, in <module>
    from terminaltables.ascii_table import AsciiTable  # noqa
ImportError: No module named 'terminaltables'

Thank you in advance!

**Comment by tosher** [comment]
Are the plugin was installed with Package Control?

**Comment by m-jumpi** [comment]
Yes, sure, it was installed with Package Control.

**Comment by tosher** [comment]
I haven't this error, but I'm using portable version.. will try to check with an installer.

**Comment by tosher** [comment]
Please, try the new version:
https://github.com/tosher/TSQLEasy/releases/tag/v1.5.1
It will be available at Package Control after some time.

**Comment by m-jumpi** [comment]
I've tried this new version and it seems it's working properly.

Thank you very much for that.
